name: Update Daily News

on:
  schedule:
    - cron: "0 1 * * *" # Roda diariamente à 1h UTC
  workflow_dispatch: # Permite execução manual

jobs:
  update_news:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necessário para commitar no README
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Ou a versão que preferir

      - name: Install dependencies
        run: npm install node-fetch@2 # Especifica a versão do node-fetch compatível com CommonJS

      - name: Fetch and Update News
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: |
          node .github/scripts/fetch-news.js

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          # Verifica se há alterações antes de commitar
          if ! git diff --staged --quiet; then
            git commit -m "📰 Chore: Update daily news section in README"
            git push
          else
            echo "No changes to commit for daily news."
          fi
