name: Update Daily Quote
on:
  schedule:
    - cron: "0 0 * * *" # Roda diariamente à meia-noite UTC
  workflow_dispatch: # Permite execução manual

jobs:
  update_quote:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necessário para commitar no README
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Quote
        uses: siddharth2016/github-readme-quotes@main # Usando uma alternativa popular
        with:
          README_FILE: "README.md" # Caminho para o seu README
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token para permitir commits
          COMMIT_MESSAGE: "💬 Chore: Update daily quote"
          QUOTES_CATEGORY: "programming" # Categoria das citações (opcional)
          TARGET_SECTION: "QUOTE" # Nome da seção definida no README (ex: <!-- QUOTE:START -->)
