name: Update Daily Quote
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update_quote:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Quote
        uses: avinash201199/daily-quotes@master
        with:
          README_FILE: "README.md"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: "💬 Chore: Update daily quote"
          QUOTES_CATEGORY: "programming"
          TARGET_SECTION: "QUOTE"
