name: Generate GitHub Snake Animation

on:
  schedule:
    - cron: "0 6 * * *" # Roda diariamente às 6h UTC
  workflow_dispatch: # Permite execução manual
  push:
    branches:
      - main # Ou o nome da sua branch principal

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necessário para commitar o arquivo gerado

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }} # Pega o nome do usuário do repositório
          # Formato de saída: svg ou gif
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?color_snake=orange
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg dist/github-contribution-grid-snake-dark.svg dist/github-contribution-grid-snake.gif
          # Verifica se há alterações antes de commitar
          if ! git diff --staged --quiet; then
            git commit -m "🐍 Chore: Update contribution snake animation"
            git push
          else
            echo "No changes to commit for snake animation."
          fi
